# Generated by Django 5.2 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supplier', 'Proveedor'), ('customer', 'Cliente')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supplier', 'Proveedor'), ('customer', 'Cliente')], default='supplier', max_length=10),
        ),
    ]
