# Generated by Django 5.2 on 2025-04-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='role',
        ),
    ]
