# Generated by Django 5.1.7 on 2025-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_role_remove_supplier_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supplier', 'Proveedor'), ('customer', 'Cliente')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supplier', 'Proveedor'), ('customer', 'Cliente')], default='supplier', max_length=10),
        ),
    ]
