# Generated by Django 5.2 on 2025-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_stock_remove_product_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/sin-imagen.jpg', null=True, upload_to='img/product_images/'),
        ),
    ]
