# Generated by Django 5.2 on 2025-05-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdelivery',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
