# Generated by Django 5.2.1 on 2025-06-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_minimum_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='minimum_stock',
            new_name='stock',
        ),
    ]
