# Generated by Django 5.2.1 on 2025-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_stock_product_provision'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=10),
        ),
        migrations.DeleteModel(
            name='SupplierStoreRelation',
        ),
    ]
